[package]
name = "mudu_macro_test"
version = "0.1.0"
edition = "2024"

[dependencies]
mudu_macro = { workspace = true }
mudu = { workspace = true }
mudu_contract = { workspace = true }
mudu_type = { workspace = true }
mudu_binding = {workspace = true}
wit-bindgen = { workspace = true }