[[modules.wallet]]
module_name = "wallet"
proc_name = "deposit"

[[modules.wallet.param_desc.fields]]
name = "user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "amount"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "transfer"

[[modules.wallet.param_desc.fields]]
name = "from_user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "to_user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "amount"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "purchase"

[[modules.wallet.param_desc.fields]]
name = "user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "amount"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "description"

[modules.wallet.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "create_user"

[[modules.wallet.param_desc.fields]]
name = "user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "name"

[modules.wallet.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.wallet.param_desc.fields]]
name = "email"

[modules.wallet.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "delete_user"

[[modules.wallet.param_desc.fields]]
name = "user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "transfer_funds"

[[modules.wallet.param_desc.fields]]
name = "from_user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "to_user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "amount"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "update_user"

[[modules.wallet.param_desc.fields]]
name = "user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "name"

[modules.wallet.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.wallet.param_desc.fields]]
name = "email"

[modules.wallet.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[modules.wallet.return_desc]
fields = []

[[modules.wallet]]
module_name = "wallet"
proc_name = "withdraw"

[[modules.wallet.param_desc.fields]]
name = "user_id"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.wallet.param_desc.fields]]
name = "amount"

[modules.wallet.param_desc.fields.dat_type]
id = "I32"
param = ""

[modules.wallet.return_desc]
fields = []
