[[modules.module]]
module_name = "module"
proc_name = "proc_mtp"

[[modules.module.param_desc.fields]]
name = "a"

[modules.module.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.module.param_desc.fields]]
name = "b"

[modules.module.param_desc.fields.dat_type]
id = "I64"
param = ""

[[modules.module.param_desc.fields]]
name = "c"

[modules.module.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.module.return_desc.fields]]
name = "0"

[modules.module.return_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.module.return_desc.fields]]
name = "1"

[modules.module.return_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.module]]
module_name = "module"
proc_name = "proc2_mtp"

[[modules.module.param_desc.fields]]
name = "a"

[modules.module.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.module.param_desc.fields]]
name = "b"

[modules.module.param_desc.fields.dat_type]
id = "I64"
param = ""

[[modules.module.param_desc.fields]]
name = "c"

[modules.module.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.module.return_desc.fields]]
name = "0"

[modules.module.return_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.module.return_desc.fields]]
name = "1"

[modules.module.return_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.module]]
module_name = "module"
proc_name = "proc_sys_call_mtp"

[[modules.module.param_desc.fields]]
name = "a"

[modules.module.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.module.param_desc.fields]]
name = "b"

[modules.module.param_desc.fields.dat_type]
id = "I64"
param = ""

[[modules.module.param_desc.fields]]
name = "c"

[modules.module.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.module.return_desc.fields]]
name = "0"

[modules.module.return_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.module.return_desc.fields]]
name = "1"

[modules.module.return_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'
