[[modules.vote]]
module_name = "vote"
proc_name = "add_option"

[[modules.vote.param_desc.fields]]
name = "vote_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "option_text"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.return_desc.fields]]
name = "field_0"

[modules.vote.return_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote]]
module_name = "vote"
proc_name = "cast_vote"

[[modules.vote.param_desc.fields]]
name = "user_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "vote_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "option_ids"

[modules.vote.param_desc.fields.dat_type]
id = "Array"
param = '{"dat_type":{"id":"String","param":"{\"length\":65536}"},"max_size":null}'

[modules.vote.return_desc]
fields = []

[[modules.vote]]
module_name = "vote"
proc_name = "create_user"

[[modules.vote.param_desc.fields]]
name = "phone"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.return_desc.fields]]
name = "field_0"

[modules.vote.return_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote]]
module_name = "vote"
proc_name = "create_vote"

[[modules.vote.param_desc.fields]]
name = "creator_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "topic"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "vote_type"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "max_choices"

[modules.vote.param_desc.fields.dat_type]
id = "I64"
param = ""

[[modules.vote.param_desc.fields]]
name = "end_time"

[modules.vote.param_desc.fields.dat_type]
id = "I64"
param = ""

[[modules.vote.param_desc.fields]]
name = "visibility_rule"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.return_desc.fields]]
name = "field_0"

[modules.vote.return_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote]]
module_name = "vote"
proc_name = "get_vote_result"

[[modules.vote.param_desc.fields]]
name = "vote_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.return_desc.fields]]
name = "field_0"

[modules.vote.return_desc.fields.dat_type]
id = "Object"
param = '{"name":"vote_result","field":[["vote_id",{"id":"String","param":"{\"length\":65536}"}],["topic",{"id":"String","param":"{\"length\":65536}"}],["vote_ended",{"id":"I32","param":""}],["total_votes",{"id":"I32","param":""}],["options",{"id":"String","param":"{\"length\":65536}"}]]}'

[[modules.vote]]
module_name = "vote"
proc_name = "get_voting_history"

[[modules.vote.param_desc.fields]]
name = "user_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.return_desc.fields]]
name = "field_0"

[modules.vote.return_desc.fields.dat_type]
id = "Object"
param = '{"name":"vote_history_item","field":[["vote_id",{"id":"String","param":"{\"length\":65536}"}],["topic",{"id":"String","param":"{\"length\":65536}"}],["action_time",{"id":"I32","param":""}],["is_withdrawn",{"id":"I32","param":""}],["vote_ended",{"id":"I32","param":""}]]}'

[[modules.vote]]
module_name = "vote"
proc_name = "withdraw_vote"

[[modules.vote.param_desc.fields]]
name = "user_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[[modules.vote.param_desc.fields]]
name = "vote_id"

[modules.vote.param_desc.fields.dat_type]
id = "String"
param = '{"length":65536}'

[modules.vote.return_desc]
fields = []
