[[modules.mod_0]]
proc_name = "proc"
module_name = "mod_0"

[[modules.mod_0.param_desc.fields]]
name = "a"

[modules.mod_0.param_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.mod_0.param_desc.fields]]
name = "b"

[modules.mod_0.param_desc.fields.dat_type]
id = "I64"
param = ""

[[modules.mod_0.param_desc.fields]]
name = "c"

[modules.mod_0.param_desc.fields.dat_type]
id = "String"
param = "{\"length\":65535}"

[[modules.mod_0.return_desc.fields]]
name = "t_0"

[modules.mod_0.return_desc.fields.dat_type]
id = "I32"
param = ""

[[modules.mod_0.return_desc.fields]]
name = "t_1"

[modules.mod_0.return_desc.fields.dat_type]
id = "String"
param = "{\"length\":65535}"
