[env]

WASM_NAME = "mod_0"
PACKAGE_NAME = "app1"
PROFILE = "release"
TARGET = "wasm32-wasip2"
WASM_FILE = "${CARGO_MAKE_WORKING_DIRECTORY}/../target/${TARGET}/${PROFILE}/${WASM_NAME}.wasm"
PACKAGE_TARGET = "${CARGO_MAKE_WORKING_DIRECTORY}/../target/${TARGET}/${PROFILE}/${PACKAGE_NAME}.mpk"

[tasks.transpile]
command = "python"
args = [
    "${CARGO_MAKE_WORKING_DIRECTORY}/../script/build/transpiler.py",
    "--config", "${CARGO_MAKE_WORKING_DIRECTORY}/build-cfg/transpiler-cfg.toml",
    "--source", "${CARGO_MAKE_WORKING_DIRECTORY}/src/wasm_mtp",
    "--target", "${CARGO_MAKE_WORKING_DIRECTORY}/src/generated",
    "--artifact", "${CARGO_MAKE_WORKING_DIRECTORY}/src/artifact",
    "--package-desc", "${CARGO_MAKE_WORKING_DIRECTORY}/package/package.desc.json"
]


[tasks.cargo-build]

dependencies = ["transpile"]

command = "cargo"
args = ["build", "--target", "${TARGET}", "--${PROFILE}"]


[tasks.package]
dependencies = ["transpile", "cargo-build"]
command = "mpk"
args = [
    "create",
    "--package-cfg", "${CARGO_MAKE_WORKING_DIRECTORY}/package/package.cfg.toml",
    "--package-desc", "${CARGO_MAKE_WORKING_DIRECTORY}/package/package.desc.json",
    "--ddl-sql", "${CARGO_MAKE_WORKING_DIRECTORY}/sql/ddl.sql",
    "--initdb-sql", "${CARGO_MAKE_WORKING_DIRECTORY}/sql/init.sql",
    "--wasm-files", "${WASM_FILE}",
    "--output", "${PACKAGE_TARGET}"
]


[tasks.default]
alias = "package"